### ISSUE TITLE
User can search for a place

### ISSUE THREAD

**Issue by henryrding** [henryrding/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for a place.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will be able to type in a search box an address, city, or ZIP code and then press the search button to populate a list of matching places under the search box area.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121365432/221668623-a59c77a6-6f45-43d2-820c-ec9f81417887.png)
![image](https://user-images.githubusercontent.com/121365432/221668752-ae9838b8-8972-4b8e-ace5-9610c59214e6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML for the header in the `header-container`.
- [x] Below the header, create the HTML for the form search input.
- [x] Complete the HTML for the search input using the appropriate responsive layout classes.
  - [x] Write CSS for mobile devices first.
  - [x] Adjust styling to fluidly adapt to desktop.
- [x] Make input of the search form `required`.
- [x] Add a `submit` event listener to the form element that:
  - [x] prevents the page from refreshing when the form is submitted.
  - [x] stores the form's input value in a variable.
  - [x] if variable is a city name, change so that the first letter of each word is uppercase with the rest lowercase.
  - [x] Get data from geocode api passing variable as parameter.
    - [x] Query the DOM for the `'#place-list'` element.
    - [x] create a `new XMLHttpRequest()` object.
    - [x] `open()` the `xhr` object to send a `'GET'` request to `'https://geocode.xyz/' + variable + '?json=1'`.
    - [x] set the response type.
    - [x] listen for the `'load'` event on the xhr object in order to:
      - [x] for each unique location that matches the query, create an `<li>`, create a `<button>`, set its `textContent` to `city, prov, postal`, set its `'data-longt'` to `longitude`, set its `'data-latt'` to `latitude`, and append it to the `'#place-list'` element.
    - [x] `send()` the request to bein loading the data from the server.
- [x]  Add CSS styling to list.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
