### ISSUE TITLE
Feature: User can see current weather of a place

### ISSUE THREAD

**Issue by henryrding** [henryrding/ajax-project#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see current weather of a place.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click the current weather button to see a popup of the current temp and weather condition.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121365432/222862464-ac84106a-7e8e-4c65-a81f-9f1a81717fbc.png)
![image](https://user-images.githubusercontent.com/121365432/222862522-4b7a67e3-f1de-4c17-a554-f2cf71cc8f9e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create dummy 'place' in HTML with added `'Current'` button and style according to figma.
- [x] Update `renderPlace` function to include HTML for `'Current'` button with correct CSS styling.
- [x] Create `current-place-overlay` and style according to figma.
- [x] Update `renderWeek` function with `renderCurrentWeather` function that does the following:
  - [x] Sets `$currentWeatherPlace.textContent` to the name of the current place.
  - [x] Sets `$currentWeatherTemp.textContent` to the temperature of the current place.
  - [x] Sets `$currentWeathercode.textContent` to the meaning of the weathercode of the current place.
    - [x] Create handleWeathercode function that sets `#current-weather-icon` to an appropriate icon and returns a string describing the weathercode of the current place.
- [x] Add event listener to `'Current'` button that does the following when clicked:
  - [x] Update `textContent` to match the place clicked with weather information.
  - [x] Check conditional for which icon to display.
  - [x] Check conditional for background color.
  - [x] show overlay.
- [x] Add event listener to `OK` button that hides the overlay when clicked.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
