### ISSUE TITLE
User can save a place to their favorites list

### ISSUE THREAD

**Issue by henryrding** [henryrding/ajax-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save a place to their favorites list
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121365432/221985635-ffaa1273-2d1c-4445-a8cc-1cd6fea166f6.png)
![image](https://user-images.githubusercontent.com/121365432/221985789-dd047dce-e397-4bbf-9362-a90a8f28b02b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] update the `'submit'` event listener to clear previous search results before creating a new DOM tree.
- [x] add an event listener to the `ul` in the search view which does the following when an add button is clicked:
  - [x] show a confirmation modal.
  - [x] when user clicks cancel, hide the modal.
  - [x] when user clicks locations:
    - [x] hide the modal.
    - [x] swap to the locations view.
  - [x] creates a new object that has 3 properties: name, longitude, and latitude.
  - [x] conditional to check if data model's array of places contains that object:
    - [x] if it doesn't, adds the new object to the end of the data model's array of places.
- [x] in `data.js`, add a `'beforeunload'` event listener to the `window` object that serializes the data model as JSON and stores the JSON in `localStorage`.
- [x] at the bottom of `data.js`, include a conditional satement that:
  - [x] checks to see if there is a JSON data model stored in `localStorage`.
  - [x] if there is, parse it and assign it to the initial `data` variable so that the user can continue adding places to the pre-existing data model.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
