### ISSUE TITLE
User can view a list of their favorite places

### ISSUE THREAD

**Issue by henryrding** [henryrding/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a list of their favorite places.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click to see their saved locations either with the anchor on the nav bar or by clicking the button that pops up after adding a place to their locations.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/121365432/222015998-edc77c7e-5a5b-482f-8f13-26aedb6be84a.png)
![image](https://user-images.githubusercontent.com/121365432/222016028-72b0e60a-d410-48cb-907f-40b7a392bf19.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Use `https://github.com/Learning-Fuze/lfz-cors` proxy to handle requests.
- [x] define a function named `renderPlace` with a single parameter named `place`. This parameter represents a single object from a single place from the `data.places` array. The function should generate and return a DOM tree for a single place that matches the places you created in the unordered list.
- [x] create an event listener on the `document` which listens for the `DOMContentLoaded` event. In the callback function for that event, loop through the `data.places` array and generate a DOM tree for each entry in the array, and append that DOM tree to the unordered list.
- [x] remove the example HTML places from `index.html` once the user's places are successfully being appended to the DOM on page load and replace them with a message indicating that no places have been added.
- [x] create a function named `toggleNoPlaces` which toggles the no places text to show or hide when the function is called.
- [x] create `swapView` function with a single parameter representing the name of the view to show (the value will be either `search`, `locations`, `settings`, or `more-info`). This function should show the view whose name was provided as an argument, as well as change the `$viewHeading.textContent` to the appopriate title.
  - [x] group html so that everything in each view is together.
- [x] add functionality to anchor `Locations` to show `locations`.
- [x] update the `click` callback for the `add-button` to do the following:
  - [x] render a DOM tree for the newly submitted place object using the `renderPlace` function.
  - [x] appends the new DOM tree to the unordered list.
  - [x] conditionally uses the `toggleNoPlaces` function as needed to remove the no places text.
- [x] update the `DOMContentLoaded` callback function to show the view which was displayed prior to page refresh:
  - [x] uses the viewSwap function to show the view which was displayed prior to page refresh.
  - [x] conditionally uses the `toggleNoEntries` function as needed to show or remove the no places text.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
