### ISSUE TITLE
User can change units to metric or imperial

### ISSUE THREAD

**Issue by henryrding** [henryrding/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can change units to metric or imperial.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will be able to go to the settings page and pick to view temperatures/measurements in celcius/mm or farenheit/in.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![image](https://user-images.githubusercontent.com/121365432/222251901-35b5f1ba-60c6-4c3f-bcfd-672faf3077c7.png)
![image](https://user-images.githubusercontent.com/121365432/222251949-d660202e-ffab-43f0-96f1-8c5bf6a57883.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML for the form element in the `settings` view.
- [x] Create CSS to match figma.
  - [x] Make sure styling adapts between desktop and mobile views.
- [x] In `data.js`, create a `unit` property in the `data` object that holds a string of either `metric` or `imperial`.
- [x] Add global variables in `main.js` that will be used for API's URLs to `GET` values in the correct temperature unit.
- [x] Use variables to change `xhr.open('GET', ...)` requests.
- [x] Add a `'submit'` event listener to the form element that:
  - [x] prevents the page from refreshing when the form is submitted.
  - [x] updates/stores the form's input value in `data.unit`
  - [x] updates global variables to `data.unit` value if it is different.
  - [x] reload DOM elements.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
