### ISSUE TITLE
User can remove a place from their favorites list

### ISSUE THREAD

**Issue by henryrding** [henryrding/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove a place from their favorites list.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click `more info` to view information about the place and be able to delete that place from their locations list.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121365432/222296681-a17d32af-d90d-4349-9c5d-c5a816dd07b8.png)
![image](https://user-images.githubusercontent.com/121365432/222296773-49e56745-cf61-4a37-83a8-fec7d8fdcb77.png)
![image](https://user-images.githubusercontent.com/121365432/222296790-6675f918-e6e6-4cef-a957-ec792d790e09.png)
![image](https://user-images.githubusercontent.com/121365432/222296819-c97031ff-ee14-4be1-95d9-4650405634b9.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create HTML for the `more-info` view.
- [x] Add placeholders and style them according to figma.
- [x] Add an event listener to the ul in the `locations` view which does the following when a `more-info` button is clicked:
  - [x] change the $viewHeading.textContent to the `data-name` property of the button.
  - [x] swapView to `more-info`.
  - [x] set data.currentPlace in `data.js` to the object that shares `name`, `longitude`, and `latitude` in `data.places` as `data-name`, `data-long`, and `data-latt` properties of the button.
- [x] Create HTML and add CSS for delete confirmation modal.
- [x] Add an event listener to the `delete-button` which does the following when clicked:
  - [x] Show a confirmation modal.
  - [x] When user clicks no, hide the modal.
  - [x] When user clicks yes:
    - [x] remove the corresponding place object from the data model's places array.
    - [x] remove the place's li element from the `locations-list` DOM.
    - [x] set data.currentPlace in `data.js` back to `null`.
    - [x] conditionally uses the toggleNoPlaces function to show the no entries text if needed.
    - [x] hide the modal.
    - [x] swap to the locations view.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
