### ISSUE TITLE
User can view hourly weather conditions of places in their list

### ISSUE THREAD

**Issue by henryrding** [henryrding/ajax-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view hourly weather conditions of places in their list.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When user clicks more info button, they will see a large image breaking down weather for the week which also has a table under it with hourly weather conditions each day. Each day will have its own table that can be view swapped with buttons at the top of the table.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121365432/222512222-581f603f-ba65-4f11-808f-21cb996d9220.png)
![image](https://user-images.githubusercontent.com/121365432/222512271-bd32dd98-9045-4d44-a26c-47241ba90db6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
- [x] Create an event listener on the document which listens for the DOMContentLoaded event. In the callback function for that event:
  - [x] Generate and return a DOM tree for the current place in `data.currentPlace`.
    - [x] GET the `imgUrl` from API and set it to the `src` attribute.
    - [x] Give the image an `alt` attribute describing the image.
  - [x] Append that DOM tree to the `more-info-page`.
- [x] Update `$locations` event listener to do the following:
  - [x] Conditional if `$moreInfoPage` has children elements, remove them and then:
  - [x] Generate and return a DOM tree for the current place in `data.currentPlace`.
    - [x] GET the `imgUrl` from API and set it to the `src` attribute.
    - [x] Give the image an `alt` attribute describing the image.
  - [x] Append that DOM tree to the `more-info-page`.
- [x] Remove placeholder image once the image for the current place is successfully being appended to the DOM on page load.
- [x] Create a row of buttons for each day of the week and style according to figma.
- [x] Make the text for buttons 2-7 change based on what day it is in the location's timezone by getting the day of the weeks with `Date.prototype.getDay()` and the date according to time zone from API.
- [x] Create dummy table in HTML and style according to figma.
- [x] create a function named `renderTable` with a single parameter named `dayIndex`. This parameter represents what day the user wants a table for. The function should generate and return a DOM tree for a single day that matches the day of the current view from the selected button.
  - [x] Make sure to get table values from API.
- [x] Create event listener for row of buttons to call `renderTable` of the applicable `dayIndex`.
- [x] Make different weather information show on table based on screen width.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
